spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: modyeo.authentication@gmail.com
    password: ztddswmtzfaqqcjm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    secret: Z2VvLWdhdGhlcmluZy1zeXN0ZW0tbW9keWVvLWFwaS1zZXJ2ZXItc3ByaW5nLWJvb3QtanBhLWp3dC1zcHJpbmctc2VjdXJpdHktd2lydHRlci1hbmpvbmdnaWwtamFuZ21pbnNlb2stMjAyMi0wNi0wOQo=

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        show_sql: true
      default_batch_fetch_size: 1000
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect

  redis:
    host: localhost
    port: 6379
    password: modyeo!@
#
#logging:
#  level:
#    org.hibernate.sql: debug

profiles:
  active: live