version: "3.7"
services:
  modyeo-mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=modyeo
      - MYSQL_ROOT_PASSWORD=modyeo-be
      - MYSQL_USER=api
      - MYSQL_PASSWORD=modyeo!@
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
  modyeo-redis:
    image: redis:6.0.2
    command: redis-server /usr/local/etc/redis/redis.conf --port 6379
    ports:
      - 6379:6379
    platform: linux/amd64
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/users.acl:/usr/local/etc/redis/users.acl:rw